name: Cypress test
on: [push]
jobs:
  cypress-run: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout GeoEditor
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./client
          start: CI=true npm run cypress
